// Auto-generated by TropicalEval`GenerateCppMonteCarlo
// 6 convergent integrands

#include <complex>
#include <cmath>
#include <random>
#include <fstream>
#include <vector>
#include <iostream>
#include <string>
#include <cassert>
#include <cstdlib>
#include <array>
#ifdef _OPENMP
#include <omp.h>
#endif

using cx = std::complex<double>;

inline cx integrand_conv_0(const double* y, const double* params) {
    // Convergent sector 1
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp(2.0 * log_y[1]);
    P0 += (1.0/1000.0) * std::exp(1.0 * log_y[0] + 2.0 * log_y[1]);
    P0 += 1.0 * std::exp(2.0 * log_y[0]);

    cx result = (1.0/1000.0);
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_conv_1(const double* y, const double* params) {
    // Convergent sector 2
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    // lifted-sector domain indicator
    double log_ypstar = (6.907755278982137 - (-0.6 * log_y[0] + 0.3333333333333333 * log_y[1])) * (1.0/1.);
    if (log_ypstar > 0.0) return cx(0.0, 0.0);

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((2.0/5.0) * log_y[0] + (2.0/3.0) * log_y[1]);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp((2.0/5.0) * log_y[0]);
    P0 += 1000000.0 * std::exp((6.0/5.0) * log_y[0] + (2.0/3.0) * log_y[1]);

    cx result = (2.0/15.0);
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_conv_2(const double* y, const double* params) {
    // Convergent sector 3
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    // lifted-sector domain indicator
    double log_ypstar = (6.907755278982137 - (-0.6 * log_y[0] + -1. * log_y[1])) * (1.0/1.);
    if (log_ypstar > 0.0) return cx(0.0, 0.0);

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((2.0/5.0) * log_y[0]);
    P0 += 1.0 * std::exp(0.0);
    P0 += 1.0 * std::exp((2.0/5.0) * log_y[0] + 1.0 * log_y[1]);
    P0 += 1000000.0 * std::exp((6.0/5.0) * log_y[0] + 2.0 * log_y[1]);

    cx result = (1.0/5.0);
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_conv_3(const double* y, const double* params) {
    // Convergent sector 6
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    cx P0(0.0, 0.0);
    P0 += (1.0/100.0) * std::exp((2.0/3.0) * log_y[0] + (4.0/7.0) * log_y[1]);
    P0 += 1.0 * std::exp((2.0/3.0) * log_y[0] + (6.0/7.0) * log_y[1]);
    P0 += (1.0/100.0) * std::exp((1.0/3.0) * log_y[0] + (4.0/7.0) * log_y[1]);
    P0 += 1.0 * std::exp(0.0);

    cx result = (1.0/2100000.0);
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_conv_4(const double* y, const double* params) {
    // Convergent sector 7
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    // lifted-sector domain indicator
    double log_ypstar = (6.907755278982137 - (-0.8571428571428571 * log_y[0] + -2. * log_y[1])) * (1.0/2.);
    if (log_ypstar > 0.0) return cx(0.0, 0.0);

    cx P0(0.0, 0.0);
    P0 += 1.0 * std::exp((4.0/7.0) * log_y[0]);
    P0 += 1000.0 * std::exp((6.0/7.0) * log_y[0] + 2.0 * log_y[1]);
    P0 += 1.0 * std::exp((4.0/7.0) * log_y[0] + 2.0 * log_y[1]);
    P0 += 1.0 * std::exp(0.0);

    cx result = ((1.0/35.0) * (1.0/std::sqrt(10.0)));
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

inline cx integrand_conv_5(const double* y, const double* params) {
    // Convergent sector 8
    double log_y[2];
    for (int i = 0; i < 2; i++)
        log_y[i] = (y[i] > 1e-300) ? std::log(y[i]) : -700.0;

    // lifted-sector domain indicator
    double log_ypstar = (6.907755278982137 - (0.1875 * log_y[0] + -0.21428571428571427 * log_y[1])) * (1.0/1.);
    if (log_ypstar > 0.0) return cx(0.0, 0.0);

    cx P0(0.0, 0.0);
    P0 += 1000000.0 * std::exp((1.0/2.0) * log_y[0] + (4.0/7.0) * log_y[1]);
    P0 += 1.0 * std::exp(1.0 * log_y[0]);
    P0 += 1.0 * std::exp((3.0/4.0) * log_y[0] + (1.0/7.0) * log_y[1]);
    P0 += 1000000000000.0 * std::exp((6.0/7.0) * log_y[1]);

    cx result = (250000000.0/7.0);
    result *= std::exp(-2.0 * std::log(P0));
    return result;
}

// Function pointer type
using IntegrandFunc = cx(*)(const double*, const double*);

IntegrandFunc integrand_table[] = {
    integrand_conv_0,
    integrand_conv_1,
    integrand_conv_2,
    integrand_conv_3,
    integrand_conv_4,
    integrand_conv_5
};

int integrand_dim[] = {2, 2, 2, 2, 2, 2};
const int N_INTEGRANDS = 6;
const int N_PARAMS = 0;
const int MAX_DIM = 20;

// ---- CUBA Vegas support (Integrator -> "VEGAS") ----
extern "C" {
#include <cuba.h>
}
static const double VEGAS_EPSREL    = 1.e-9;
static const double VEGAS_EPSABS    = 1e-300;
static const int    VEGAS_SEED      = 0;
static const int    VEGAS_NSTART    = 1000;
static const int    VEGAS_NINCREASE = 500;
static const int    VEGAS_NBATCH    = 1000;
static const int    VEGAS_MINEVAL   = 0;

struct SectorCtx { IntegrandFunc fn; const double* params; };
static int vegas_wrap(const int* ndim, const cubareal x[], const int* /*ncomp*/,
                      cubareal ff[], void* ud) {
    const SectorCtx* ctx = static_cast<const SectorCtx*>(ud);
    double y[MAX_DIM];
    for (int i = 0; i < *ndim; ++i) y[i] = (double)x[i];
    cx v = ctx->fn(y, ctx->params);
    ff[0] = v.real();
    ff[1] = v.imag();
    return 0;
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input_file> <output_file> [n_samples] [n_threads] [seed_base]" << std::endl;
        return 1;
    }

    std::string input_file = argv[1];
    std::string output_file = argv[2];
    int n_samples = (argc > 3) ? std::atoi(argv[3]) : 3000000;
    int n_threads = (argc > 4) ? std::atoi(argv[4]) : 1;
    // Optional runtime seed override (argv[5]); falls back to compile-time SeedBase.
    uint64_t seed_base = (argc > 5) ? std::strtoull(argv[5], nullptr, 10) : 42ULL;
#ifdef _OPENMP
    if (n_threads == 1) n_threads = omp_get_max_threads();
    omp_set_num_threads(n_threads);
#endif

    // Read kinematic data
    std::ifstream fin(input_file);
    if (!fin) {
        std::cerr << "Cannot open " << input_file << std::endl;
        return 1;
    }

    std::vector<std::vector<double>> kinematic_data;
    if (N_PARAMS == 0) {
        // No kinematic parameters: read count from file, default 1
        int count = 1;
        fin >> count;
        if (count < 1) count = 1;
        for (int i = 0; i < count; i++)
            kinematic_data.push_back({});
    } else {
        double val;
        std::vector<double> row;
        while (fin >> val) {
            row.push_back(val);
            if ((int)row.size() == N_PARAMS) {
                kinematic_data.push_back(row);
                row.clear();
            }
        }
    }
    fin.close();
    int n_kp = (int)kinematic_data.size();
    std::cerr << "Read " << n_kp << " kinematic points" << std::endl;

    std::vector<std::array<double, 4>> results(n_kp);

    (void)seed_base;  // VEGAS uses VEGAS_SEED (Sobol) below, not the MC seed
    const int zero = 0;
    cubacores(&zero, &zero);   // single process: deterministic, macOS-safe

    #pragma omp parallel for schedule(dynamic)
    for (int kp = 0; kp < n_kp; kp++) {
        static double dummy_params[1] = {0.0};
        const double* params = (N_PARAMS > 0) ? kinematic_data[kp].data() : dummy_params;

        double total_re = 0.0, total_im = 0.0;
        double total_var_re = 0.0, total_var_im = 0.0;

        for (int s = 0; s < N_INTEGRANDS; s++) {
            int dim = integrand_dim[s];
            SectorCtx ctx{ integrand_table[s], params };
            int neval = 0, fail = 0;
            cubareal integ[2], err[2], prob[2];
            Vegas(dim, 2, vegas_wrap, &ctx, 1,
                  VEGAS_EPSREL, VEGAS_EPSABS, 0 /*flags*/, VEGAS_SEED,
                  VEGAS_MINEVAL, n_samples /*maxeval per sector*/,
                  VEGAS_NSTART, VEGAS_NINCREASE, VEGAS_NBATCH,
                  0 /*gridno*/, nullptr, nullptr,
                  &neval, &fail, integ, err, prob);
            total_re     += integ[0]; total_im     += integ[1];
            total_var_re += err[0]*err[0]; total_var_im += err[1]*err[1];
#ifdef TROPICAL_MC_DEBUG
            if (kp == 0)
                std::cerr << "Sector " << s << " (Vegas): est=(" << integ[0] << ","
                          << integ[1] << ") err=(" << err[0] << "," << err[1]
                          << ") fail=" << fail << " prob=" << prob[0]
                          << " neval=" << neval << std::endl;
#endif
        }

        results[kp] = {total_re, total_im,
                       std::sqrt(total_var_re), std::sqrt(total_var_im)};
    }

    // Write results
    std::ofstream fout(output_file);
    if (!fout) {
        std::cerr << "Cannot open " << output_file << std::endl;
        return 1;
    }
    fout.precision(17);
    for (int kp = 0; kp < n_kp; kp++) {
        fout << results[kp][0] << " " << results[kp][1] << " "
             << results[kp][2] << " " << results[kp][3] << "\n";
    }
    fout.close();

    std::cerr << "Done. Processed " << n_kp << " kinematic points." << std::endl;
    return 0;
}
